
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDIR = 6;
  public static final int MENOS = 4;
  public static final int MENOR = 11;
  public static final int ELSE = 19;
  public static final int RBRACE = 15;
  public static final int RPAREN = 13;
  public static final int IGUAL = 7;
  public static final int WHILE = 20;
  public static final int PONTO = 17;
  public static final int SEMI = 2;
  public static final int RETURN = 21;
  public static final int NUMERO_FLUTUANTE = 23;
  public static final int IF = 18;
  public static final int LPAREN = 12;
  public static final int LBRACE = 14;
  public static final int VIRGULA = 16;
  public static final int MAIS = 3;
  public static final int IGUAL_IGUAL = 9;
  public static final int EOF = 0;
  public static final int DIFERENTE = 8;
  public static final int NUMERO_INTEIRO = 22;
  public static final int error = 1;
  public static final int MAIOR = 10;
  public static final int IDENTIFICADOR = 24;
  public static final int VEZES = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "MAIS",
  "MENOS",
  "VEZES",
  "DIVIDIR",
  "IGUAL",
  "DIFERENTE",
  "IGUAL_IGUAL",
  "MAIOR",
  "MENOR",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "VIRGULA",
  "PONTO",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "NUMERO_INTEIRO",
  "NUMERO_FLUTUANTE",
  "IDENTIFICADOR"
  };
}

